# Generated by Django 4.1.2 on 2022-12-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="cafeteria",
            name="contact",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="cafeteria",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="cafeteria",
            name="poc",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="caterer",
            name="lower_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="caterer",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="caterer",
            name="sheet_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="caterer",
            name="upper_description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="contact",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="contact",
            name="hostel_sec",
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="occupation",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="form",
            name="heading",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="form",
            name="url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="penalty",
            name="penalty",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="rule",
            name="rule",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="update",
            name="update",
            field=models.CharField(max_length=120),
        ),
    ]
