# Generated by Django 4.1.2 on 2023-01-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_photos_options_photos_occupation_photos_poc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photos",
            name="occupation",
            field=models.CharField(
                default="",
                help_text="This contains the occupation of the person in the photograph",
                max_length=50,
                verbose_name="Occupation",
            ),
        ),
        migrations.AlterField(
            model_name="photos",
            name="poc",
            field=models.CharField(
                default="",
                help_text="This contains the name of the person in the photograph",
                max_length=30,
                verbose_name="Point of Contact",
            ),
        ),
    ]
