# Generated by Django 4.1.7 on 2023-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_allocation_id_allocation_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebate',
            name='approved',
            field=models.BooleanField(default='False', help_text='tells if the rebate is approved'),
        ),
    ]
