# Generated by Django 4.1.7 on 2023-04-12 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebate',
            name='date_applied',
            field=models.DateField(default=datetime.date(2023, 4, 12), help_text='Date on which the rebate was applied'),
        ),
    ]
