# Generated by Django 4.1.7 on 2023-03-06 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rebate_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebate',
            name='approved',
            field=models.BooleanField(default=False, help_text='tells if the rebate is approved'),
        ),
    ]
