# Generated by Django 4.1.7 on 2023-03-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_rebate_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
