# Generated by Django 4.1.7 on 2023-03-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='roll_no',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student'),
        ),
    ]
