# Generated by Django 4.1.7 on 2023-03-06 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_allocation_roll_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='roll_no',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student'),
        ),
    ]
