# Generated by Django 4.1.7 on 2023-04-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_rebateautumnsem_rebatespringsem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='august',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='december',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='july',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='november',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='october',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='september',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
