# Generated by Django 4.1.7 on 2023-04-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_rebatespringsem_april_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='email',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='email',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
