# Generated by Django 4.1.7 on 2023-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_rebateautumnsem_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.RemoveField(
            model_name='rebateautumnsem',
            name='august',
        ),
        migrations.RemoveField(
            model_name='rebateautumnsem',
            name='december',
        ),
        migrations.RemoveField(
            model_name='rebateautumnsem',
            name='july',
        ),
        migrations.RemoveField(
            model_name='rebateautumnsem',
            name='november',
        ),
        migrations.RemoveField(
            model_name='rebateautumnsem',
            name='october',
        ),
        migrations.RemoveField(
            model_name='rebateautumnsem',
            name='september',
        ),
        migrations.RemoveField(
            model_name='rebatespringsem',
            name='april',
        ),
        migrations.RemoveField(
            model_name='rebatespringsem',
            name='feburary',
        ),
        migrations.RemoveField(
            model_name='rebatespringsem',
            name='january',
        ),
        migrations.RemoveField(
            model_name='rebatespringsem',
            name='june',
        ),
        migrations.RemoveField(
            model_name='rebatespringsem',
            name='march',
        ),
        migrations.RemoveField(
            model_name='rebatespringsem',
            name='may',
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='NovemberBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='augustBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='augustLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='augustShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='decemberBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='decemberLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='decemberShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='julyBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='julyLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='julyShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='novemberLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='novemberShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='octoberBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='octoberLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='octoberShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='septemberBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='septemberLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebateautumnsem',
            name='septemberShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='aprilBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='aprilLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='aprilShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='feburaryBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='feburaryLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='feburaryShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='januaryBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='januaryLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='januaryShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='juneBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='juneLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='juneShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='marchBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='marchLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='marchShort',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='mayBill',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='mayLong',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='rebatespringsem',
            name='mayShort',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
