# Generated by Django 4.1.7 on 2023-05-07 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_delete_file_remove_rebateautumnsem_august_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongRebateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(help_text='The text in the text field contains the rule that will show as one of the long rebate rules of the rule page.', verbose_name='Rule')),
            ],
            options={
                'verbose_name': 'Long Rebate',
                'verbose_name_plural': 'Long Rebates',
            },
        ),
        migrations.AlterModelOptions(
            name='longrebate',
            options={'verbose_name': 'Long Rebate Details', 'verbose_name_plural': 'Long Rebate Details'},
        ),
        migrations.RemoveField(
            model_name='longrebate',
            name='rule',
        ),
        migrations.AddField(
            model_name='longrebate',
            name='allocation_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_id_long', to='home.allocation'),
        ),
        migrations.AddField(
            model_name='longrebate',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
        migrations.AddField(
            model_name='longrebate',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date on which the rebate was applied'),
        ),
        migrations.AddField(
            model_name='longrebate',
            name='days',
            field=models.IntegerField(default=0, verbose_name='days'),
        ),
        migrations.AddField(
            model_name='longrebate',
            name='email',
            field=models.CharField(default='', max_length=30, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='longrebate',
            name='month',
            field=models.CharField(default='', max_length=10, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='NovemberBill',
            field=models.IntegerField(default=0, null=True, verbose_name='November Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='augustBill',
            field=models.IntegerField(default=0, null=True, verbose_name='August Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='augustLong',
            field=models.IntegerField(default=0, null=True, verbose_name='August Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='augustShort',
            field=models.IntegerField(default=0, null=True, verbose_name='August Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='decemberBill',
            field=models.IntegerField(default=0, null=True, verbose_name='December Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='decemberLong',
            field=models.IntegerField(default=0, null=True, verbose_name='December Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='decemberShort',
            field=models.IntegerField(default=0, null=True, verbose_name='December Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='highTeaAugust',
            field=models.BooleanField(default=True, verbose_name='August High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='highTeaDecember',
            field=models.BooleanField(default=True, verbose_name='December High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='highTeaJuly',
            field=models.BooleanField(default=True, verbose_name='July High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='highTeaNovember',
            field=models.BooleanField(default=True, verbose_name='November High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='highTeaOctober',
            field=models.BooleanField(default=True, verbose_name='October High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='highTeaSeptember',
            field=models.BooleanField(default=True, verbose_name='September High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='julyBill',
            field=models.IntegerField(default=0, null=True, verbose_name='July Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='julyLong',
            field=models.IntegerField(default=0, null=True, verbose_name='July Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='julyShort',
            field=models.IntegerField(default=0, null=True, verbose_name='July Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='novemberLong',
            field=models.IntegerField(default=0, null=True, verbose_name='November Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='novemberShort',
            field=models.IntegerField(default=0, null=True, verbose_name='November Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='octoberBill',
            field=models.IntegerField(default=0, null=True, verbose_name='October Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='octoberLong',
            field=models.IntegerField(default=0, null=True, verbose_name='October Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='octoberShort',
            field=models.IntegerField(default=0, null=True, verbose_name='October Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='septemberBill',
            field=models.IntegerField(default=0, null=True, verbose_name='September Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='septemberLong',
            field=models.IntegerField(default=0, null=True, verbose_name='September Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='septemberShort',
            field=models.IntegerField(default=0, null=True, verbose_name='September Short'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='aprilBill',
            field=models.IntegerField(default=0, null=True, verbose_name='April Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='aprilLong',
            field=models.IntegerField(default=0, null=True, verbose_name='April Long'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='aprilShort',
            field=models.IntegerField(default=0, null=True, verbose_name='April Short'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='email',
            field=models.CharField(default='', max_length=30, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='feburaryBill',
            field=models.IntegerField(default=0, null=True, verbose_name='Feburary Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='feburaryLong',
            field=models.IntegerField(default=0, null=True, verbose_name='Feburary Long'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='feburaryShort',
            field=models.IntegerField(default=0, null=True, verbose_name='Feburary Short'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='highTeaApril',
            field=models.BooleanField(default=True, verbose_name='April High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='highTeaFeburary',
            field=models.BooleanField(default=True, verbose_name='Feburary High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='highTeaJanuary',
            field=models.BooleanField(default=True, verbose_name='January High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='highTeaJune',
            field=models.BooleanField(default=True, verbose_name='June High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='highTeaMarch',
            field=models.BooleanField(default=True, verbose_name='March High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='highTeaMay',
            field=models.BooleanField(default=True, verbose_name='May High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='januaryBill',
            field=models.IntegerField(default=0, null=True, verbose_name='January Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='januaryLong',
            field=models.IntegerField(default=0, null=True, verbose_name='January Long'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='januaryShort',
            field=models.IntegerField(default=0, null=True, verbose_name='January Short'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='juneBill',
            field=models.IntegerField(default=0, null=True, verbose_name='June Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='juneLong',
            field=models.IntegerField(default=0, null=True, verbose_name='June Long'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='juneShort',
            field=models.IntegerField(default=0, null=True, verbose_name='June Short'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='marchBill',
            field=models.IntegerField(default=0, null=True, verbose_name='March Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='marchLong',
            field=models.IntegerField(default=0, null=True, verbose_name='March Long'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='marchShort',
            field=models.IntegerField(default=0, null=True, verbose_name='March Short'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='mayBill',
            field=models.IntegerField(default=0, null=True, verbose_name='May Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='mayLong',
            field=models.IntegerField(default=0, null=True, verbose_name='May Long'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='mayShort',
            field=models.IntegerField(default=0, null=True, verbose_name='May Short'),
        ),
        migrations.AlterField(
            model_name='student',
            name='degree',
            field=models.CharField(help_text='This contains the degree of the Student', max_length=10, verbose_name='Academic Program'),
        ),
    ]
