# Generated by Django 4.1.7 on 2023-05-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_rename_allocation_id_longrebate_allocation_id_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30, verbose_name='email')),
            ],
            options={
                'verbose_name': 'Unregistered Students',
                'verbose_name_plural': 'Ungegistered Students',
            },
        ),
    ]
