# Generated by Django 4.1.7 on 2023-05-14 17:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_unregisteredstudent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the rebate')),
                ('Caterer', models.CharField(default='', max_length=30)),
                ('allocation_id', models.CharField(default='', max_length=30)),
                ('start_date', models.DateField(blank=True, help_text='start date of the rebate', null=True)),
                ('end_date', models.DateField(blank=True, help_text='end date of the rebate', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatererBillsSpring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('januaryBill', models.IntegerField(default=0, null=True, verbose_name='January Bill')),
                ('feburaryBill', models.IntegerField(default=0, null=True, verbose_name='Feburary Bill')),
                ('marchBill', models.IntegerField(default=0, null=True, verbose_name='March Bill')),
                ('aprilBill', models.IntegerField(default=0, null=True, verbose_name='April Bill')),
                ('mayBill', models.IntegerField(default=0, null=True, verbose_name='May Bill')),
                ('juneBill', models.IntegerField(default=0, null=True, verbose_name='June Bill')),
                ('Caterer', models.ForeignKey(default='', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer')),
            ],
            options={
                'verbose_name': 'Caterer Bill Spring Semester',
                'verbose_name_plural': 'Caterer Bills Spring Semester',
            },
        ),
        migrations.CreateModel(
            name='CatererBillsAutumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('julyBill', models.IntegerField(default=0, null=True, verbose_name='July Bill')),
                ('augustBill', models.IntegerField(default=0, null=True, verbose_name='August Bill')),
                ('septemberBill', models.IntegerField(default=0, null=True, verbose_name='September Bill')),
                ('octoberBill', models.IntegerField(default=0, null=True, verbose_name='October Bill')),
                ('novemberBill', models.IntegerField(default=0, null=True, verbose_name='November Bill')),
                ('decemberBill', models.IntegerField(default=0, null=True, verbose_name='December Bill')),
                ('Caterer', models.ForeignKey(default='', max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer')),
            ],
            options={
                'verbose_name': 'Caterer Bill Autumn Semester',
                'verbose_name_plural': 'Caterer Bills Autumn Semester',
            },
        ),
    ]
