# Generated by Django 4.1.7 on 2023-05-15 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_todayrebate_catererbillsspring_catererbillsautumn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todayrebate',
            options={'verbose_name': "Today's Rebate", 'verbose_name_plural': "Today's Rebate"},
        ),
        migrations.AddField(
            model_name='unregisteredstudent',
            name='month',
            field=models.CharField(default='', max_length=30, verbose_name='month'),
        ),
    ]
