# Generated by Django 4.1.7 on 2023-05-17 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_delete_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='caterer_name',
            field=models.CharField(blank=True, default='', help_text='The text in this text field contains the caterer name.', max_length=50, null=True, verbose_name='Caterer Name'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='first_pref',
            field=models.CharField(blank=True, default=None, help_text='This contians the first preference caterer of the student', max_length=10, null=True, verbose_name='First Preference'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='high_tea',
            field=models.BooleanField(blank=True, default=False, help_text='This contains the info if high tea is taken or not', null=True, verbose_name='High Tea'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='month',
            field=models.CharField(blank=True, default='', help_text='This contains for which month the allocation id is alloted', max_length=10, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='second_pref',
            field=models.CharField(blank=True, default=None, help_text='This contians the first preference caterer of the student', max_length=10, null=True, verbose_name='Second Preference'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='third_pref',
            field=models.CharField(blank=True, default=None, help_text='This contians the first preference caterer of the student', max_length=10, null=True, verbose_name='Third Preference'),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Image of Cafeteria'),
        ),
        migrations.AlterField(
            model_name='rebateautumnsem',
            name='email',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student'),
        ),
        migrations.AlterField(
            model_name='rebatespringsem',
            name='email',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student'),
        ),
    ]
