# Generated by Django 4.1.7 on 2023-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_remove_catererbillsautumn22_augustbill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftLongRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30, verbose_name='email')),
                ('start_date', models.DateField(blank=True, help_text='start date of the rebate', null=True)),
                ('end_date', models.DateField(blank=True, help_text='end date of the rebate', null=True)),
            ],
            options={
                'verbose_name': 'Left Long Rebate',
                'verbose_name_plural': 'Left Long Rebate',
            },
        ),
        migrations.RemoveField(
            model_name='rebatespringsem',
            name='email',
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period2_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Feburary Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period2_high_tea',
            field=models.BooleanField(default=True, verbose_name='Feburary High Tea'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period2_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Feburary Long'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period2_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Feburary Short'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period3_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='March Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period3_high_tea',
            field=models.BooleanField(default=True, verbose_name='March High Tea'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period3_long',
            field=models.IntegerField(default=0, null=True, verbose_name='March Long'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period3_short',
            field=models.IntegerField(default=0, null=True, verbose_name='March Short'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period4_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='April Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period4_high_tea',
            field=models.BooleanField(default=True, verbose_name='April High Tea'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period4_long',
            field=models.IntegerField(default=0, null=True, verbose_name='April Long'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period4_short',
            field=models.IntegerField(default=0, null=True, verbose_name='April Short'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period5_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='May Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period5_high_tea',
            field=models.BooleanField(default=True, verbose_name='May High Tea'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period5_long',
            field=models.IntegerField(default=0, null=True, verbose_name='May Long'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period5_short',
            field=models.IntegerField(default=0, null=True, verbose_name='May Short'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period6_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='June Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period6_high_tea',
            field=models.BooleanField(default=True, verbose_name='June High Tea'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period6_long',
            field=models.IntegerField(default=0, null=True, verbose_name='June Long'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period6_short',
            field=models.IntegerField(default=0, null=True, verbose_name='June Short'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='January Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_high_tea',
            field=models.BooleanField(default=True, verbose_name='January High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_long',
            field=models.IntegerField(default=0, null=True, verbose_name='January Long'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_short',
            field=models.IntegerField(default=0, null=True, verbose_name='January Short'),
        ),
        migrations.DeleteModel(
            name='RebateAutumnSem',
        ),
        migrations.DeleteModel(
            name='RebateSpringSem',
        ),
    ]
