# Generated by Django 4.1.7 on 2023-05-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_leftlongrebate_remove_rebatespringsem_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unregisteredstudent',
            name='month',
        ),
    ]
