# Generated by Django 4.1.7 on 2023-05-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_alter_catererbillsautumn22_period1_bills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longrebate',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student'),
        ),
    ]
