# Generated by Django 5.0.8 on 2024-11-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rebatespring23',
            name='email',
        ),
        migrations.DeleteModel(
            name='RebateAutumn22',
        ),
        migrations.DeleteModel(
            name='RebateSpring23',
        ),
    ]
