# Generated by Django 5.0.8 on 2024-11-17 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodayRebate',
        ),
    ]
