# Generated by Django 5.0.3 on 2024-08-17 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allocationautumn23",
            name="month",
        ),
        migrations.RemoveField(
            model_name="allocationautumn23",
            name="roll_no",
        ),
        migrations.RemoveField(
            model_name="allocationspring23",
            name="month",
        ),
        migrations.RemoveField(
            model_name="allocationspring23",
            name="roll_no",
        ),
        migrations.AlterField(
            model_name="scan",
            name="student_id",
            field=models.ForeignKey(
                default=0,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="home.student",
            ),
        ),
        migrations.RemoveField(
            model_name="catererbillsautumn22",
            name="caterer",
        ),
        migrations.RemoveField(
            model_name="catererbillsautumn23",
            name="caterer",
        ),
        migrations.RemoveField(
            model_name="catererbillsspring23",
            name="caterer",
        ),
        migrations.AddField(
            model_name="longrebate",
            name="reason",
            field=models.TextField(
                blank=True,
                choices=[
                    ("", "Choose the reason"),
                    (
                        "Incomplete form. Please submit a new rebate application",
                        "Incomplete form",
                    ),
                    (
                        "Signature of approving authority missing. Please submit a new rebate application",
                        "Signature missing",
                    ),
                    (
                        "Attached file is not the rebate form. Please submit a new rebate application with correct attachment",
                        "Wrong attached document",
                    ),
                    (
                        "There is a date mismatch between the one written in the form and the one in the attached form. Please submit a new rebate application",
                        "There is a date mismatch between the one written in the form and the one in the attached form",
                    ),
                ],
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="sno",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="AllocationAutumn22",
        ),
        migrations.DeleteModel(
            name="AllocationAutumn23",
        ),
        migrations.DeleteModel(
            name="AllocationSpring23",
        ),
        migrations.DeleteModel(
            name="CatererBillsAutumn22",
        ),
        migrations.DeleteModel(
            name="CatererBillsAutumn23",
        ),
        migrations.DeleteModel(
            name="CatererBillsSpring23",
        ),
    ]
