# Generated by Django 5.0.8 on 2024-11-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_todayrebate'),
        ('home', '0002_remove_rebatespring23_email_delete_rebateautumn22_and_more'),
    ]

    operations = [
    ]
