# Generated by Django 5.0.3 on 2024-08-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_remove_allocationautumn22_month_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocationform",
            name="show_allocated",
            field=models.BooleanField(default=False, verbose_name="show_allocated"),
        ),
    ]
