# Generated by Django 5.0.10 on 2024-12-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_allocation_registration_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="allocation_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Indicates if the student is allowed to participate in the allocation process",
            ),
        ),
    ]
