# Generated by Django 4.1.2 on 2022-12-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_longrebate_options_alter_shortrebate_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cafeteria",
            name="image",
            field=models.ImageField(
                default=1, upload_to="", verbose_name="Image of Cafeteria"
            ),
            preserve_default=False,
        ),
    ]
