# Generated by Django 5.0.8 on 2024-09-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allocationform_show_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='registration_time',
            field=models.DateTimeField(auto_now_add=True, help_text='This contains the time of registration', null=True, verbose_name='Registration time'),
        ),
    ]
