# Generated by Django 5.0.8 on 2024-12-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_allocation_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room_no',
            field=models.CharField(blank=True, default='', help_text='This contains the room number of the Student', max_length=10, null=True, verbose_name='Room Number of Student'),
        ),
    ]
