# Generated by Django 5.0.8 on 2024-08-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_longrebate_local_file_alter_longrebate_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longrebate',
            name='local_file',
        ),
        migrations.AlterField(
            model_name='longrebate',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='documents/', verbose_name='File'),
        ),
    ]
