# Generated by Django 5.0.8 on 2024-09-03 16:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allocationform_show_allocated'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='registration_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This contains the time of registration', null=True, verbose_name='Registration time'),
        ),
    ]
