# Generated by Django 5.0.8 on 2024-09-25 08:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_allocation_registration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='registration_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='This contains the date and time of registration', null=True, verbose_name='Registration time'),
        ),
    ]
