# Generated by Django 5.0.8 on 2024-12-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_student_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbills',
            name='email',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
