# Generated by Django 4.1.2 on 2023-01-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_cafeteria_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeteria',
            name='image',
            field=models.ImageField(upload_to='static/images', verbose_name='Image of Cafeteria'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='occupation',
            field=models.CharField(help_text='This contains the occupation of the contact to be added', max_length=50, verbose_name='Occupation'),
        ),
    ]
