# Generated by Django 5.0.8 on 2025-02-25 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_studentbills_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocationform',
            name='period',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='home.period'),
        ),
    ]
