# Generated by Django 5.0.13 on 2025-03-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_allocationform_period"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[
                            ("General", "General Menu"),
                            ("Sick Food", "Sick Food Menu"),
                            ("Jain", "Jain Menu"),
                        ],
                        help_text="The type of menu (General, Sick Food, Jain). Only one instance per type is allowed.",
                        max_length=20,
                        unique=True,
                        verbose_name="Menu Type",
                    ),
                ),
                (
                    "sheet_url",
                    models.URLField(
                        help_text="The Google Sheets URL containing the respective menu.",
                        verbose_name="Menu URL",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
            },
        ),
    ]
