# Generated by Django 5.0.13 on 2025-03-22 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This contains the name of the Student in SDC",
                        max_length=50,
                        verbose_name="Name of Student",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Profile image of the Student in SDC",
                        null=True,
                        upload_to="sdc_images/",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Head", "Head"),
                            ("Advisory", "Advisory"),
                            ("Member", "Member"),
                        ],
                        help_text="This contains the position of the Student in SDC",
                        max_length=20,
                        verbose_name="Position in SDC",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        choices=[(2024, "2024"), (2025, "2025")],
                        help_text="Select the year for SDC membership",
                        verbose_name="Year",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        help_text="Reference to the Student table",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sdc_profile",
                        to="home.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "SDC Member",
                "verbose_name_plural": "SDC Members",
            },
        ),
    ]
