# Generated by Django 4.1.7 on 2023-03-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_photos_occupation_alter_photos_poc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, default=None, help_text='This contains the Allocation Id', max_length=30, null=True, verbose_name='Allocation Id')),
                ('month', models.CharField(help_text='This contains for which month the allocation id is alloted', max_length=10, verbose_name='Month')),
                ('caterer_name', models.CharField(help_text='The text in this text field contains the caterer name.', max_length=50, verbose_name='Caterer Name')),
                ('high_tea', models.BooleanField(help_text='This contains the info if high tea is taken or not', verbose_name='High Tea')),
                ('first_pref', models.CharField(default=None, help_text='This contians the first preference caterer of the student', max_length=10, verbose_name='First Preference')),
                ('second_pref', models.CharField(default=None, help_text='This contians the first preference caterer of the student', max_length=10, verbose_name='Second Preference')),
                ('third_pref', models.CharField(default=None, help_text='This contians the first preference caterer of the student', max_length=10, verbose_name='Third Preference')),
            ],
            options={
                'verbose_name': 'Allocation Details',
                'verbose_name_plural': 'Allocation Details',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='This contains the name of the Student', max_length=30, verbose_name='Name of Student')),
                ('roll_no', models.CharField(help_text='This contains the roll number of the Student', max_length=10, verbose_name='Roll number of Student')),
                ('department', models.CharField(help_text='This contains the department of the Student', max_length=30, verbose_name='Department of Student')),
                ('degree', models.CharField(help_text='This contains the degree of the Student', max_length=10, verbose_name='Degree of Student')),
                ('hostel', models.CharField(help_text='This contains the hostel of the Student', max_length=3, verbose_name='Hostel of Student')),
                ('room_no', models.CharField(help_text='This contains the room number of the Student', max_length=5, verbose_name='Room Number of Student')),
            ],
            options={
                'verbose_name': 'Student Details',
                'verbose_name_plural': 'Student Details',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the scan details')),
                ('breakfast', models.BooleanField(help_text='This contains if the breeakfast was eaten by the student', verbose_name='Breakfast')),
                ('lunch', models.BooleanField(help_text='This contains if the lunch was eaten by the student', verbose_name='lunch')),
                ('high_tea', models.BooleanField(help_text='This contains if the high tea was eaten by the student', verbose_name='high_tea')),
                ('dinner', models.BooleanField(help_text='This contains if the dinner was eaten by the student', verbose_name='dinner')),
                ('student_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.allocation')),
            ],
            options={
                'verbose_name': 'Scan Details',
                'verbose_name_plural': 'Scan Details',
            },
        ),
        migrations.CreateModel(
            name='Rebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='start date of the rebate')),
                ('end_date', models.DateField(help_text='end date of the rebate')),
                ('approved', models.BooleanField(default=False, help_text='tells if the rebate is approved')),
                ('allocation_id', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.allocation')),
            ],
            options={
                'verbose_name': 'Rebate Details',
                'verbose_name_plural': 'Rebate Details',
            },
        ),
        migrations.AddField(
            model_name='allocation',
            name='roll_no',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student'),
        ),
    ]
