# Generated by Django 5.0.8 on 2025-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_sdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default=None, help_text='This contains the photo of the Student', null=True, upload_to='photos/', verbose_name='Photo'),
        ),
    ]
