# Generated by Django 5.0.13 on 2026-01-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='first_pref',
            field=models.CharField(blank=True, default=None, help_text='This contians the first preference caterer of the student', max_length=12, null=True, verbose_name='First Preference'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='second_pref',
            field=models.CharField(blank=True, default=None, help_text='This contians the first preference caterer of the student', max_length=12, null=True, verbose_name='Second Preference'),
        ),
        migrations.AlterField(
            model_name='allocation',
            name='third_pref',
            field=models.CharField(blank=True, default=None, help_text='This contians the first preference caterer of the student', max_length=12, null=True, verbose_name='Third Preference'),
        ),
    ]
