# Generated by Django 5.1.14 on 2026-06-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConstants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_rebate_stretch_limit', models.IntegerField(default=7, help_text='Maximum number of days for a single short rebate application.', verbose_name='Short Rebate Stretch Limit')),
                ('short_rebate_period_limit', models.IntegerField(default=8, help_text='Maximum total days allowed for short rebates within a single period.', verbose_name='Short Rebate Period Limit')),
                ('min_rebate_days', models.IntegerField(default=2, help_text='Minimum number of days required for a rebate application.', verbose_name='Minimum Rebate Days')),
                ('days_prior_notice', models.IntegerField(default=2, help_text='Minimum days before leave commencement the form must be filled.', verbose_name='Days Prior Notice')),
            ],
            options={
                'verbose_name': 'Global Constant',
                'verbose_name_plural': 'Global Constants',
            },
        ),
    ]
