# Generated by Django 5.1.14 on 2026-06-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_globalconstants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconstants',
            name='short_rebate_period_limit',
            field=models.IntegerField(default=10, help_text='Maximum total days allowed for short rebates within a single period.', verbose_name='Short Rebate Period Limit'),
        ),
        migrations.AlterField(
            model_name='globalconstants',
            name='short_rebate_stretch_limit',
            field=models.IntegerField(default=10, help_text='Maximum number of days for a single short rebate application.', verbose_name='Short Rebate Stretch Limit'),
        ),
    ]
