# Generated by Django 5.1.14 on 2026-06-08 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_allocation_first_pref_and_more'),
        ('home', '0011_alter_globalconstants_short_rebate_period_limit_and_more'),
    ]

    operations = [
    ]
