# Generated by Django 5.1.14 on 2026-08-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_merge_20260819_1633"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="hostel",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This contains the hostel of the Student",
                max_length=5,
                null=True,
                verbose_name="Hostel of Student",
            ),
        ),
    ]