# Generated by Django 4.1.7 on 2023-04-27 13:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_caterer_student_limit_alter_rebate_date_applied'),
    ]

    operations = [
        migrations.CreateModel(
            name='RebateAutumnSem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=0, max_length=30)),
                ('july', models.IntegerField(default=0)),
                ('highTeaJuly', models.BooleanField(default=True)),
                ('august', models.IntegerField(default=0)),
                ('highTeaAugust', models.BooleanField(default=True)),
                ('september', models.IntegerField(default=0)),
                ('highTeaSeptember', models.BooleanField(default=True)),
                ('october', models.IntegerField(default=0)),
                ('highTeaOctober', models.BooleanField(default=True)),
                ('november', models.IntegerField(default=0)),
                ('highTeaNovember', models.BooleanField(default=True)),
                ('december', models.IntegerField(default=0)),
                ('highTeaDecember', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rebate Bill Autumn Semester',
                'verbose_name_plural': 'Rebate Bills Autumn Semester',
            },
        ),
        migrations.CreateModel(
            name='RebateSpringSem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default=0, max_length=30)),
                ('january', models.IntegerField(default=0)),
                ('highTeaJanuary', models.BooleanField(default=True)),
                ('feburary', models.IntegerField(default=0)),
                ('highTeaFeburary', models.BooleanField(default=True)),
                ('march', models.IntegerField(default=0)),
                ('highTeaMarch', models.BooleanField(default=True)),
                ('april', models.IntegerField(default=0)),
                ('highTeaApril', models.BooleanField(default=True)),
                ('may', models.IntegerField(default=0)),
                ('highTeaMay', models.BooleanField(default=True)),
                ('june', models.IntegerField(default=0)),
                ('highTeaJune', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Rebate Bill Spring Semester',
                'verbose_name_plural': 'Rebate Bills Spring Semester',
            },
        ),
        migrations.AlterField(
            model_name='caterer',
            name='lower_description',
            field=models.TextField(default='', help_text='This contains the description of the respective caterer that will show on the lower side.', verbose_name='Lower Discription'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='occupation',
            field=models.TextField(help_text='This contains the occupation of the contact to be added', verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='rebate',
            name='allocation_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_id', to='home.allocation'),
        ),
        migrations.AlterField(
            model_name='rebate',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now, help_text='Date on which the rebate was applied'),
        ),
    ]
