# Generated by Django 4.1.7 on 2023-05-09 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_longrebatedata_alter_longrebate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longrebate',
            old_name='allocation_id',
            new_name='allocation_id_id',
        ),
    ]
