# Generated by Django 4.1.7 on 2023-05-16 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_delete_longrebatedata_delete_penalty_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photos',
        ),
    ]
