# Generated by Django 4.1.7 on 2023-05-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_allocation_caterer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(help_text='This contains the department of the Student', max_length=30, null=True, verbose_name='Department of Student'),
        ),
    ]
