# Generated by Django 4.1.7 on 2023-05-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_periodautumn22_periodautumn23_periodspring23_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catererbillsautumn22',
            name='augustBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn22',
            name='decemberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn22',
            name='julyBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn22',
            name='novemberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn22',
            name='octoberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn22',
            name='septemberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn23',
            name='augustBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn23',
            name='decemberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn23',
            name='julyBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn23',
            name='novemberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn23',
            name='octoberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn23',
            name='septemberBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsspring23',
            name='aprilBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsspring23',
            name='feburaryBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsspring23',
            name='januaryBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsspring23',
            name='juneBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsspring23',
            name='marchBill',
        ),
        migrations.RemoveField(
            model_name='catererbillsspring23',
            name='mayBill',
        ),
        migrations.RemoveField(
            model_name='periodautumn22',
            name='period',
        ),
        migrations.RemoveField(
            model_name='periodautumn23',
            name='period',
        ),
        migrations.RemoveField(
            model_name='periodspring23',
            name='period',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='NovemberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='augustBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='augustLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='augustShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='decemberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='decemberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='decemberShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='highTeaAugust',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='highTeaDecember',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='highTeaJuly',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='highTeaNovember',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='highTeaOctober',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='highTeaSeptember',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='julyBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='julyLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='julyShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='novemberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='novemberShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='octoberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='octoberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='octoberShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='septemberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='septemberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn22',
            name='septemberShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='NovemberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='augustBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='augustLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='augustShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='decemberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='decemberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='decemberShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='highTeaAugust',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='highTeaDecember',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='highTeaJuly',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='highTeaNovember',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='highTeaOctober',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='highTeaSeptember',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='julyBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='julyLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='julyShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='novemberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='novemberShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='octoberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='octoberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='octoberShort',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='septemberBill',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='septemberLong',
        ),
        migrations.RemoveField(
            model_name='rebateautumn23',
            name='septemberShort',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='aprilBill',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='aprilLong',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='aprilShort',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='feburaryBill',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='feburaryLong',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='feburaryShort',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='highTeaApril',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='highTeaFeburary',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='highTeaJanuary',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='highTeaJune',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='highTeaMarch',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='highTeaMay',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='januaryBill',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='januaryLong',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='januaryShort',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='juneBill',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='juneLong',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='juneShort',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='marchBill',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='marchLong',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='marchShort',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='mayBill',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='mayLong',
        ),
        migrations.RemoveField(
            model_name='rebatespring23',
            name='mayShort',
        ),
        migrations.AddField(
            model_name='catererbillsautumn22',
            name='period1_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='July Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn22',
            name='period2_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='August Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn22',
            name='period3_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='September Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn22',
            name='period4_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='October Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn22',
            name='period5_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='November Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn22',
            name='period6_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='December Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn23',
            name='period1_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='July Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn23',
            name='period2_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='August Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn23',
            name='period3_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='September Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn23',
            name='period4_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='October Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn23',
            name='period5_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='November Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn23',
            name='period6_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='December Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsspring23',
            name='period1_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='January Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsspring23',
            name='period2_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Feburary Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsspring23',
            name='period3_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='March Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsspring23',
            name='period4_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='April Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsspring23',
            name='period5_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='May Bill'),
        ),
        migrations.AddField(
            model_name='catererbillsspring23',
            name='period6_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='June Bill'),
        ),
        migrations.AddField(
            model_name='periodautumn22',
            name='end_date',
            field=models.DateField(blank=True, help_text='This contains the end date of this Period of this semester', null=True),
        ),
        migrations.AddField(
            model_name='periodautumn22',
            name='start_date',
            field=models.DateField(blank=True, help_text='This contains the start date of this Period for this semester', null=True),
        ),
        migrations.AddField(
            model_name='periodautumn23',
            name='end_date',
            field=models.DateField(blank=True, help_text='This contains the end date of this Period of this semester', null=True),
        ),
        migrations.AddField(
            model_name='periodautumn23',
            name='start_date',
            field=models.DateField(blank=True, help_text='This contains the start date of this Period for this semester', null=True),
        ),
        migrations.AddField(
            model_name='periodspring23',
            name='end_date',
            field=models.DateField(blank=True, help_text='This contains the end date of this Period of this semester', null=True),
        ),
        migrations.AddField(
            model_name='periodspring23',
            name='start_date',
            field=models.DateField(blank=True, help_text='This contains the start date of this Period for this semester', null=True),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period1_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='July Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period1_high_tea',
            field=models.BooleanField(default=True, verbose_name='July High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period1_long',
            field=models.IntegerField(default=0, null=True, verbose_name='July Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period1_short',
            field=models.IntegerField(default=0, null=True, verbose_name='July Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period2_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='August Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period2_high_tea',
            field=models.BooleanField(default=True, verbose_name='August High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period2_long',
            field=models.IntegerField(default=0, null=True, verbose_name='August Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period2_short',
            field=models.IntegerField(default=0, null=True, verbose_name='August Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period3_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='September Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period3_high_tea',
            field=models.BooleanField(default=True, verbose_name='September High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period3_long',
            field=models.IntegerField(default=0, null=True, verbose_name='September Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period3_short',
            field=models.IntegerField(default=0, null=True, verbose_name='September Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period4_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='October Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period4_high_tea',
            field=models.BooleanField(default=True, verbose_name='October High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period4_long',
            field=models.IntegerField(default=0, null=True, verbose_name='October Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period4_short',
            field=models.IntegerField(default=0, null=True, verbose_name='October Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period5_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='November Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period5_high_tea',
            field=models.BooleanField(default=True, verbose_name='November High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period5_long',
            field=models.IntegerField(default=0, null=True, verbose_name='November Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period5_short',
            field=models.IntegerField(default=0, null=True, verbose_name='November Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period6_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='December Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period6_high_tea',
            field=models.BooleanField(default=True, verbose_name='December High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period6_long',
            field=models.IntegerField(default=0, null=True, verbose_name='December Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn22',
            name='period6_short',
            field=models.IntegerField(default=0, null=True, verbose_name='December Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period1_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='July Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period1_high_tea',
            field=models.BooleanField(default=True, verbose_name='July High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period1_long',
            field=models.IntegerField(default=0, null=True, verbose_name='July Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period1_short',
            field=models.IntegerField(default=0, null=True, verbose_name='July Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period2_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='August Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period2_high_tea',
            field=models.BooleanField(default=True, verbose_name='August High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period2_long',
            field=models.IntegerField(default=0, null=True, verbose_name='August Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period2_short',
            field=models.IntegerField(default=0, null=True, verbose_name='August Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period3_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='September Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period3_high_tea',
            field=models.BooleanField(default=True, verbose_name='September High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period3_long',
            field=models.IntegerField(default=0, null=True, verbose_name='September Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period3_short',
            field=models.IntegerField(default=0, null=True, verbose_name='September Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period4_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='October Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period4_high_tea',
            field=models.BooleanField(default=True, verbose_name='October High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period4_long',
            field=models.IntegerField(default=0, null=True, verbose_name='October Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period4_short',
            field=models.IntegerField(default=0, null=True, verbose_name='October Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period5_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='November Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period5_high_tea',
            field=models.BooleanField(default=True, verbose_name='November High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period5_long',
            field=models.IntegerField(default=0, null=True, verbose_name='November Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period5_short',
            field=models.IntegerField(default=0, null=True, verbose_name='November Short'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period6_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='December Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period6_high_tea',
            field=models.BooleanField(default=True, verbose_name='December High Tea'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period6_long',
            field=models.IntegerField(default=0, null=True, verbose_name='December Long'),
        ),
        migrations.AddField(
            model_name='rebateautumn23',
            name='period6_short',
            field=models.IntegerField(default=0, null=True, verbose_name='December Short'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period1_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='June Rebate Amount'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period1_high_tea',
            field=models.BooleanField(default=True, verbose_name='June High Tea'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period1_long',
            field=models.IntegerField(default=0, null=True, verbose_name='June Long'),
        ),
        migrations.AddField(
            model_name='rebatespring23',
            name='period1_short',
            field=models.IntegerField(default=0, null=True, verbose_name='June Short'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn',
            name='Caterer',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer'),
        ),
        migrations.AlterField(
            model_name='catererbillsspring',
            name='Caterer',
            field=models.ForeignKey(max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer'),
        ),
    ]
