# Generated by Django 4.1.7 on 2023-05-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_remove_unregisteredstudent_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='unregisteredstudent',
            name='period',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.periodspring23'),
        ),
    ]
