# Generated by Django 4.1.7 on 2023-05-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_unregisteredstudent_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebate',
            name='allocation_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_id', to='home.allocationspring23'),
        ),
        migrations.AlterField(
            model_name='unregisteredstudent',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.periodspring23'),
        ),
    ]
