# Generated by Django 4.1.7 on 2023-05-26 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_remove_catererbillsspring23_caterer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catererbillsautumn22',
            name='Caterer',
        ),
        migrations.RemoveField(
            model_name='catererbillsautumn23',
            name='Caterer',
        ),
        migrations.AddField(
            model_name='catererbillsautumn22',
            name='caterer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer'),
        ),
        migrations.AddField(
            model_name='catererbillsautumn23',
            name='caterer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.caterer'),
        ),
    ]
