# Generated by Django 4.1.7 on 2023-05-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_catererbillsautumn22_caterer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catererbillsspring',
            name='Caterer',
        ),
        migrations.DeleteModel(
            name='CatererBillsAutumn',
        ),
        migrations.DeleteModel(
            name='CatererBillsSpring',
        ),
    ]
