# Generated by Django 4.1.7 on 2023-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_remove_catererbillsspring_caterer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catererbillsautumn22',
            name='period1_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn22',
            name='period2_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn22',
            name='period3_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn22',
            name='period4_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn22',
            name='period5_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn22',
            name='period6_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn23',
            name='period1_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn23',
            name='period2_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn23',
            name='period3_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn23',
            name='period4_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn23',
            name='period5_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsautumn23',
            name='period6_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsspring23',
            name='period1_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsspring23',
            name='period2_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsspring23',
            name='period3_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsspring23',
            name='period4_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsspring23',
            name='period5_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Bill'),
        ),
        migrations.AlterField(
            model_name='catererbillsspring23',
            name='period6_bills',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Bill'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period1_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period1_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 1 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period1_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period1_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period2_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period2_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 2 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period2_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period2_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period3_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period3_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 3 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period3_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period3_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period4_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period4_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 4 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period4_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period4_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period5_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period5_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 5 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period5_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period5_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period6_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period6_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 6 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period6_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period6_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period1_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period1_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 1 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period1_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period1_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period2_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period2_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 2 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period2_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period2_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period3_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period3_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 3 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period3_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period3_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period4_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period4_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 4 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period4_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period4_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period5_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period5_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 5 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period5_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period5_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Short'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period6_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period6_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 6 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period6_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Long'),
        ),
        migrations.AlterField(
            model_name='rebateautumn23',
            name='period6_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Short'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 1 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Long'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period1_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 1 Short'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period2_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period2_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 2 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period2_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Long'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period2_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 2 Short'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period3_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period3_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 3 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period3_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Long'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period3_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 3 Short'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period4_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period4_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 4 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period4_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Long'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period4_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 4 Short'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period5_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period5_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 5 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period5_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Long'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period5_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 5 Short'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period6_bill',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Rebate Amount'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period6_high_tea',
            field=models.BooleanField(default=True, verbose_name='Period 6 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period6_long',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Long'),
        ),
        migrations.AlterField(
            model_name='rebatespring23',
            name='period6_short',
            field=models.IntegerField(default=0, null=True, verbose_name='Period 6 Short'),
        ),
    ]
