# Generated by Django 4.1.7 on 2023-05-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_longrebate_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cafeteria',
            options={'verbose_name': 'Additional Services', 'verbose_name_plural': 'Additional Services'},
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images', verbose_name='Image of Service'),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='name',
            field=models.CharField(help_text='This contains the name of the Service', max_length=30, verbose_name='Name of Service'),
        ),
        migrations.AlterField(
            model_name='cafeteria',
            name='poc',
            field=models.CharField(help_text='This contains the name of the point of contact of the respective Service', max_length=30, verbose_name='Point of Contact'),
        ),
    ]
