# Generated by Django 4.1.7 on 2023-05-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_alter_cafeteria_options_alter_cafeteria_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='student_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.allocationspring23'),
        ),
        migrations.DeleteModel(
            name='Allocation',
        ),
    ]
