# Generated by Django 4.1.7 on 2023-05-29 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_alter_scan_student_id_delete_allocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todayrebate',
            name='allocation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.allocationspring23'),
        ),
    ]
