# Generated by Django 4.1.7 on 2023-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_alter_todayrebate_allocation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period1_high_tea',
            field=models.BooleanField(default=True, null=True, verbose_name='Period 1 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period2_high_tea',
            field=models.BooleanField(default=True, null=True, verbose_name='Period 2 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period3_high_tea',
            field=models.BooleanField(default=True, null=True, verbose_name='Period 3 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period4_high_tea',
            field=models.BooleanField(default=True, null=True, verbose_name='Period 4 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period5_high_tea',
            field=models.BooleanField(default=True, null=True, verbose_name='Period 5 High Tea'),
        ),
        migrations.AlterField(
            model_name='rebateautumn22',
            name='period6_high_tea',
            field=models.BooleanField(default=True, null=True, verbose_name='Period 6 High Tea'),
        ),
    ]
