# Generated by Django 4.1.7 on 2023-06-14 15:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_alter_rebateautumn22_period1_high_tea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caterer',
            name='visible',
            field=models.BooleanField(default=False, help_text='If the caterer is visible or not to the students', null=True, verbose_name='Visible'),
        ),
        migrations.CreateModel(
            name='AllocationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='heading')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='description')),
                ('active', models.BooleanField(blank=True, default=False, null=True, verbose_name='active')),
                ('start_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.periodspring23')),
            ],
            options={
                'verbose_name': 'Allocation Form',
                'verbose_name_plural': 'Allocation Form',
            },
        ),
    ]
