# Generated by Django 4.1.7 on 2023-06-14 15:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_caterer_visible_allocationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeftShortRebate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=30, verbose_name='email')),
                ('start_date', models.DateField(blank=True, help_text='start date of the rebate', null=True)),
                ('end_date', models.DateField(blank=True, help_text='end date of the rebate', null=True)),
                ('date_applied', models.DateField(default=django.utils.timezone.now, help_text='Date on which the rebate was applied')),
            ],
            options={
                'verbose_name': 'Left Short Rebate',
                'verbose_name_plural': 'Left Short Rebate',
            },
        ),
    ]
