# Generated by Django 4.2.2 on 2023-06-29 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_period_semester_studentbills_period_semester_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allocation',
            old_name='month',
            new_name='period',
        ),
        migrations.RemoveField(
            model_name='catererbills',
            name='period',
        ),
        migrations.RemoveField(
            model_name='studentbills',
            name='period',
        ),
        migrations.AddField(
            model_name='catererbills',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semester', verbose_name='Semester'),
        ),
        migrations.AddField(
            model_name='studentbills',
            name='semester',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.semester', verbose_name='Semester'),
        ),
        migrations.AlterField(
            model_name='allocationform',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.period'),
        ),
        migrations.AlterField(
            model_name='rebate',
            name='allocation_id',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_id', to='home.allocation'),
        ),
        migrations.AlterField(
            model_name='rebate',
            name='email',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.student', verbose_name='Student Email'),
        ),
        migrations.AlterField(
            model_name='todayrebate',
            name='allocation_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.allocation'),
        ),
        migrations.AlterField(
            model_name='unregisteredstudent',
            name='period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.period'),
        ),
    ]
