# Generated by Django 5.0.8 on 2024-10-04 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='This contains the unique id of the mess card', primary_key=True, serialize=False, unique=True)),
                ('qr_code', models.ImageField(blank=True, help_text='This contains the qr code image', null=True, upload_to='qr_codes/')),
                ('allocation', models.ForeignKey(blank=True, help_text='This contains the allocation details', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.allocation')),
                ('student', models.ForeignKey(blank=True, help_text='This contains the student details', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='This contains the date of the meal')),
                ('breakfast', models.BooleanField(default=False, help_text='This contains the breakfast status')),
                ('lunch', models.BooleanField(default=False, help_text='This contains the lunch status')),
                ('dinner', models.BooleanField(default=False, help_text='This contains the dinner status')),
                ('mess_card', models.ForeignKey(blank=True, help_text='This contains the mess card details', null=True, on_delete=django.db.models.deletion.CASCADE, to='qrscan.messcard')),
            ],
            options={
                'unique_together': {('mess_card', 'date')},
            },
        ),
    ]
