# Generated by Django 5.0.8 on 2024-09-25 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0005_alter_allocation_registration_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, help_text='This contains', null=True, upload_to='qr_codes/')),
                ('allocation', models.ForeignKey(blank=True, help_text='This contains the allocation details', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.allocation')),
            ],
        ),
    ]
