# Generated by Django 5.0.8 on 2024-09-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messcard',
            name='secret_key',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
