# Generated by Django 5.0.8 on 2024-10-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='high_tea',
            field=models.BooleanField(default=False, help_text='This contains the high tea status'),
        ),
    ]
