# Generated by Django 5.0.8 on 2024-09-25 08:40

import qrscan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0002_messcard_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcard',
            name='secret_key',
            field=models.CharField(blank=True, default=qrscan.models.generate_secret_key, max_length=64, null=True),
        ),
    ]
