# Generated by Django 5.0.8 on 2024-09-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0003_alter_messcard_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcard',
            name='qr_code',
            field=models.ImageField(blank=True, help_text='This contains the qr code image', null=True, upload_to='qr_codes/'),
        ),
    ]
