# Generated by Django 5.0.8 on 2024-09-25 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_allocation_registration_time'),
        ('qrscan', '0004_alter_messcard_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='messcard',
            name='student',
            field=models.ForeignKey(blank=True, help_text='This contains the student details', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
