# Generated by Django 5.0.8 on 2024-10-22 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('qrscan', '0004_messtiming_delete_messtimings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcard',
            name='student',
            field=models.ForeignKey(help_text='This contains the student details', on_delete=django.db.models.deletion.CASCADE, to='home.student'),
        ),
    ]
