# Generated by Django 5.0.8 on 2024-09-29 09:31

import qrscan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0005_messcard_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcard',
            name='secret_key',
            field=models.CharField(blank=True, default=qrscan.models.generate_secret_key, help_text='This contains the secret key for each student', max_length=64, null=True),
        ),
    ]
