# Generated by Django 5.0.8 on 2024-09-29 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0006_alter_messcard_secret_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='This contains the date of the meal')),
                ('breakfast', models.BooleanField(default=False, help_text='This contains the breakfast status')),
                ('lunch', models.BooleanField(default=False, help_text='This contains the lunch status')),
                ('dinner', models.BooleanField(default=False, help_text='This contains the dinner status')),
                ('mess_card', models.ForeignKey(blank=True, help_text='This contains the mess card details', null=True, on_delete=django.db.models.deletion.CASCADE, to='qrscan.messcard')),
            ],
        ),
    ]
