# Generated by Django 5.0.8 on 2024-10-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0008_alter_messcard_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messcard',
            name='secret_key',
        ),
    ]
