# Generated by Django 5.0.8 on 2024-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0009_remove_messcard_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
