# Generated by Django 5.0.8 on 2024-10-03 17:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrscan', '0010_alter_messcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messcard',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='This contains the unique id of the mess card', primary_key=True, serialize=False, unique=True),
        ),
    ]
