version: '3'

services:
  web: 
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - ./data/db.sqlite3:/root/db.sqlite3
    environment:
      - SQLITE3_DB=db.sqlite3