name: Django CI

on:
  pull_request:
    branches: [ "main"]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
    
    env:
      SECRET_KEY: 123456789
      GOOGLE_CLIENT_ID: 123456789
      GOOGLE_CLIENT_SECRET: 123456789
      EMAIL_HOST: 123456789
      EMAIL_HOST_PASSWORD: 123456789
      CLOUD_NAME: 123456789
      API_KEY_CLOUD: 123456789
      API_SECRET_CLOUD: 123456789

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python manage.py collectstatic --noinput
    - name: Run Server
      run: |
        python manage.py runserver
